((nil . ((indent-tabs-mode . nil)
	 (tab-width . 8)
	 ;;(coding . utf8)
	 (fill-column . 79)
	 (ispell-local-dictionary . "american")))
 (c-mode . ((indent-tabs-mode . nil)
            (c-file-style . "bsd")
	    (c-basic-offset . 2)))
 (java-mode . ((indent-tabs-mode . nil)
               (c-basic-offset . 2)))
 (julia-mode . ((indent-tabs-mode . nil)))
 (makefile-gmake-mode . ((indent-tabs-mode . t)))
 (makefile-automake-mode . ((indent-tabs-mode . t)))
 (sh-mode . ((indent-tabs-mode . nil)
             (sh-indentation . 2)
             (sh-basic-offset . 2)))
 (tcl-mode . ((indent-tabs-mode . nil)
              (tcl-indent-level . 2)))
 (yorick-mode . ((indent-tabs-mode . nil)
                 (c-basic-offset . 2)
                 (fill-column . 78)))
)
